version: '{build}-{branch}'
os: Windows Server 2012
platform:
  - x64
init:
- ps: |
    mkdir C:\Users\appveyor\.vagrant.d | Out-Null
    echo @'
    Vagrant::configure('2') do |config|
      config.vm.boot_timeout = 1020
    end
    '@ | Out-File -encoding UTF8 C:\Users\appveyor\.vagrant.d\Vagrantfile
- ps: |
    mkdir C:\downloads | Out-Null
    cd C:\downloads
    Start-FileDownload "https://releases.hashicorp.com/vagrant/1.9.5/vagrant_1.9.5.msi"
    Start-Process -FilePath "msiexec.exe" -ArgumentList "/a vagrant_1.9.5.msi /qb TARGETDIR=C:\Vagrant-1.9.5" -Wait
    [Net.ServicePointManager]::SecurityProtocol = 'Ssl3, Tls, Tls11, Tls12'
    Start-FileDownload "http://download.virtualbox.org/virtualbox/5.1.22/VirtualBox-5.1.22-115126-Win.exe"
    Start-Process -FilePath "VirtualBox-5.1.22-115126-Win.exe" -ArgumentList "-silent -logging -msiparams INSTALLDIR=C:\VBox-5.1.22" -Wait
    cd $env:APPVEYOR_BUILD_FOLDER
- ps: |
    While ((Test-NetConnection google.com -Port 80 -InformationLevel Quiet) -ne "True") {
        echo "waiting for network..."
        Start-Sleep 1
    }
install:
- set PATH=C:\Vagrant-1.9.5\HashiCorp\Vagrant\bin;C:\VBox-5.1.22;%PATH%
- vagrant -v
- VBoxManage -v
- ssh -V
- ipconfig /all
build_script:
- ps: Test-NetConnection google.com -Port 80
- vagrant up || ssh vagrant@127.0.0.1 -p 2222 -i .vagrant\machines\default\virtualbox\private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -vvv -C "pwd"
- vagrant ssh -c "uname -a"
test: off
