version: '{build}-{branch}'
image: Visual Studio 2017
platform:
  - x64
# Maximum number of concurrent jobs for the project
max_jobs: 1
init:
- ps: |
    [Net.ServicePointManager]::SecurityProtocol = 'Ssl3, Tls, Tls11, Tls12'
- ps: |
    While ((Test-NetConnection google.com -Port 80 -InformationLevel Quiet) -ne "True") {
        echo "waiting for network..."
        Start-Sleep 1
    }
install:
- ps: |
    choco install virtualbox
    choco install vagrant
    cd $env:APPVEYOR_BUILD_FOLDER
    
    mkdir %userprofile%\.vagrant.d | Out-Null
    echo @'
    Vagrant::configure('2') do |config|
      config.vm.boot_timeout = 2048
    end
    '@ | Out-File -encoding UTF8 %userprofile%\.vagrant.d\Vagrantfile
- refreshenv
- vagrant -v
- VBoxManage -v
- ssh -V
- ipconfig /all

# Don't actually build.
build_script:

after_build:
- ps: Test-NetConnection google.com -Port 80
- vagrant up
- vagrant ssh -c "uname -a"
- echo "Finished building playground"

test: off
