version: '{build}-{branch}'
os: Windows Server 2012
platform:
  - x64
init:
- ps: |
    mkdir C:\Users\appveyor\.vagrant.d | Out-Null
    echo @'
    Vagrant::configure('2') do |config|
      config.vm.boot_timeout = 1020
    end
    '@ | Out-File -encoding UTF8 C:\Users\appveyor\.vagrant.d\Vagrantfile
- ps: |
    [Net.ServicePointManager]::SecurityProtocol = 'Ssl3, Tls, Tls11, Tls12'
    choco install virtualbox
    choco install vagrant
    cd $env:APPVEYOR_BUILD_FOLDER
- ps: |
    While ((Test-NetConnection google.com -Port 80 -InformationLevel Quiet) -ne "True") {
        echo "waiting for network..."
        Start-Sleep 1
    }
install:
- vagrant -v
- VBoxManage -v
- ssh -V
- ipconfig /all
build_script:
- ps: Test-NetConnection google.com -Port 80
- vagrant up
- vagrant ssh -c "uname -a"
test: off
